global:
  name: default
  poses:
    sol_antepregrasp_positions: [70.44, -36.28, -19.05, -121.91, -24.66, -33.1, 11.29]
    sol_antepregrasp2_positions: [3.28, -4.64, -25.8, -91.09, -6.37, 1.36, 34.95]
    
    sol_drop_positions: [-61.69, -5.78, 81.97, -86.22, -64.84, 0.57, 22.43]
    # sol_drop_positions: [-9.65, 4.33, 55.69, -80.47, -8.75, -6.37, 32.4]

    sol_antepregrasp3_positions: [23.58, -21.95, 36.18, -110.61, -0.57, -11.74, -16.86]


reachable_grasp_triplet_node:
  table_height: -0.344 # table height in torso frame
  # Offsets in the grasp pose oriented like r_arm_tip (so x is up, y is left, z is backward)
  # + means up
  # Used to center the gripper on the object since
  # the middle of the gripper is not the point controlled by the IK solver
  # TODO this should be *-1 on the left arm
  grasp_offset_x : 0.0
  grasp_offset_y : 0.025
  grasp_offset_z : 0.0
  collision_table_margin : 0.03
